apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: test
spec:
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./clusters/test/tenants
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
  postBuild:
    substitute:
      CLUSTER_NAME: test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: test
spec:
  dependsOn:
    - name: tenants
  targetNamespace: test
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./clusters/test/infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: cluster-kubeconfig
        - op: add
          path: /spec/serviceAccountName
          value: flux-cluster-admin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: test
spec:
  dependsOn:
    - name: infra-controllers
  targetNamespace: test
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./clusters/test/infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: test
spec:
  dependsOn:
    - name: infra-configs
  targetNamespace: test
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./clusters/test/apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: cluster-kubeconfig
        - op: add
          path: /spec/serviceAccountName
          value: flux-restricted
